
-- A function to add a voice.
function CAKE.AddChatterVoice(faction, command, phrase, sound, female, menu)
		CAKE.chattervoices[#CAKE.chattervoices + 1] = {
		faction = faction,
		command = command,
		phrase = phrase,
		female = female,
		sound = sound,
		menu = menu
	};
end;

// DUDE I AM TABLING VOICES SO HARD RIGHT NOW (R.I.P Old DeathByKittens, September 2012)
CAKE.chattervoices = {};




CAKE.AddChatterVoice("Combine", "Sweeping", "Sweeping for suspect.", "npc/metropolice/hiding02.wav");
CAKE.AddChatterVoice("Combine", "11-6", "Suspect 11-6, my 10-20 is", "npc/metropolice/vo/suspect11-6my1020is.wav");
CAKE.AddChatterVoice("Combine", "Getting 647E", "Still getting that 647E from local survallience.", "npc/metropolice/vo/stillgetting647e.wav");
CAKE.AddChatterVoice("Combine", "Off-World", "Permanent off-world service assignment.", "npc/overwatch/radiovoice/permanentoffworld.wav");
CAKE.AddChatterVoice("Combine", "10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav");
CAKE.AddChatterVoice("Combine", "Judge 10-107", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav");
CAKE.AddChatterVoice("Combine", "Sundown", "GRID Sundown 4-6.", "npc/combine_soldier/vo/gridsundown46.wav");
CAKE.AddChatterVoice("Combine", "Need Help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav");
CAKE.AddChatterVoice("Combine", "Under Fire", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav");
CAKE.AddChatterVoice("Combine", "Possible 647E", "Possible 647E here, requesting AirWatch to tag!", "npc/metropolice/vo/possible647erequestairwatch.wav");
CAKE.AddChatterVoice("Combine", "Aquiring Visual", "Aquiring a visual.", "npc/metropolice/vo/acquiringonvisual.wav");
CAKE.AddChatterVoice("Combine", "10-78", "Dispatch, I need 10-78, officer in trouble!", "npc/metropolice/vo/dispatchIneed10-78.wav");
CAKE.AddChatterVoice("Combine", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav");
CAKE.AddChatterVoice("Combine", "Classify", "Classify subject name as DB.  This block ready for cleanup.", "npc/metropolice/vo/classifyasdbthisblockready.wav");
CAKE.AddChatterVoice("Combine", "Firing Expose", "Firing to expose target.", "npc/metropolice/vo/firingtoexposetarget.wav");
CAKE.AddChatterVoice("Combine", "Restricted Incursion", "Restricted incustion in progress.", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav");
CAKE.AddChatterVoice("Combine", "10-103M", "10-103M Disturbance by mentally unfit.", "npc/overwatch/radiovoice/disturbancemental10-103m.wav");
CAKE.AddChatterVoice("Combine", "Memory Replacement", "Reminder: memory replacement is the first step to rank privleges.", "npc/overwatch/radiovoice/remindermemoryreplacement.wav");
CAKE.AddChatterVoice("Combine", "10-107", "Got a 10-107 here, send AirWatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav");
CAKE.AddChatterVoice("Combine", "Close on Suspect", "All units close on suspect.", "npc/metropolice/vo/allunitscloseonsuspect.wav");
CAKE.AddChatterVoice("Combine", "Control Section", "Control section!", "npc/metropolice/vo/controlsection.wav");
CAKE.AddChatterVoice("Combine", "Report", "Local civil protection team, report status.", "npc/metropolice/vo/localcptreportstatus.wav");
CAKE.AddChatterVoice("Combine", "Loyalty Failure", "Control, I have a failure to comply with loyalty check tags, possible 10-103M.", "npc/metropolice/vo/loyaltycheckfailure.wav");
CAKE.AddChatterVoice("Combine", "Arrest", "All units, move to arrest positions.", "npc/metropolice/vo/movetoarrestpositions.wav");
CAKE.AddChatterVoice("Combine", "External", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav");
CAKE.AddChatterVoice("Combine", "Ready Judge", "Ready to judge!", "npc/metropolice/vo/readytojudge.wav");
CAKE.AddChatterVoice("Combine", "Running Low", "Running low on verdicts!  Taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav");
CAKE.AddChatterVoice("Combine", "Malcompliant", "Malcompliant 10-107 my 10-20.  Preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav");
CAKE.AddChatterVoice("Combine", "Isolate", "Isolate!", "npc/metropolice/hiding05.wav");
CAKE.AddChatterVoice("Combine", "Guilty", "You are judged guilty by civil protection team!", "npc/overwatch/radiovoice/youarejudgedguilty.wav");
CAKE.AddChatterVoice("Combine", "Team Deployed", "Team is deployed and scanning!", "npc/combine_soldier/vo/teamdeployedandscanning.wav");
CAKE.AddChatterVoice("Combine", "Come With", "You, citizen.  Come with me!", "vo/trainyard/ba_youcomewith.wav");
CAKE.AddChatterVoice("Combine", "I'm Good", "No, I'm good.", "vo/trainyard/ba_noimgood.wav");
CAKE.AddChatterVoice("Combine", "Need Privacy", "Yeah, I'm gunna need me some privacy for this.", "vo/trainyard/ba_privacy.wav");
CAKE.AddChatterVoice("Combine", "Socioside", "Socioside!", "npc/metropolice/vo/sociocide.wav");
CAKE.AddChatterVoice("Combine", "Non-Patrol", "Non-patrol region!", "npc/metropolice/vo/nonpatrolregion.wav");
CAKE.AddChatterVoice("Combine", "Investigate", "Investigate!", "npc/metropolice/vo/investigate.wav");
CAKE.AddChatterVoice("Combine", "Investigate Report", "Investigate and Report!", "npc/overwatch/radiovoice/investigateandreport.wav");
CAKE.AddChatterVoice("Combine", "Prosecute Final", "Ready to prosecute malcompliant citizen, final warning issued.", "npc/metropolice/vo/readytoprosecutefinalwarning.wav");
CAKE.AddChatterVoice("Combine", "Position Advance", "Team in position, advance.", "npc/metropolice/vo/teaminpositionadvance.wav");
CAKE.AddChatterVoice("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav");
CAKE.AddChatterVoice("Combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav");
CAKE.AddChatterVoice("Combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav");
CAKE.AddChatterVoice("Combine", "10-99", "Officer down!  I am 10-99, repeat, I am 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav");
CAKE.AddChatterVoice("Combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav");
CAKE.AddChatterVoice("Combine", "Sociostable", "We are sociostable this location.", "npc/metropolice/vo/wearesociostablethislocation.wav");
CAKE.AddChatterVoice("Combine", "10-8", "Unit is on duty.  10-8.", "npc/metropolice/vo/unitisonduty10-8.wav");
CAKE.AddChatterVoice("Combine", "Standing By", "10-8.  Standing by.", "npc/metropolice/vo/ten8standingby.wav");
CAKE.AddChatterVoice("Combine", "10-0 Viscerator", "10-0!  10-0!  Viscerator is hunting!", "npc/metropolice/vo/tenzerovisceratorishunting.wav");
CAKE.AddChatterVoice("Combine", "Need Any Help", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav");
CAKE.AddChatterVoice("Combine", "Uniform", "Uniform!", "npc/combine_soldier/vo/uniform.wav");
CAKE.AddChatterVoice("Combine", "Medical", "Request Medical!", "npc/combine_soldier/vo/requestmedical.wav");
CAKE.AddChatterVoice("Combine", "Stim", "Request stim-dose!", "npc/combine_soldier/vo/requeststimdose.wav");
CAKE.AddChatterVoice("Combine", "Sector Not Secure", "Sector is not secure!", "npc/combine_soldier/vo/sectorisnotsecure.wav");
CAKE.AddChatterVoice("Combine", "Sector Secure", "Sector is secure, no viscon!", "npc/combine_soldier/vo/sectorissecurenovison.wav");
CAKE.AddChatterVoice("Combine", "You Can Go", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav");
CAKE.AddChatterVoice("Combine", "Need Assistance", "Eleven-ninety-nine, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav");
CAKE.AddChatterVoice("Combine", "Point Secure", "Assault point secure, advance!", "npc/metropolice/vo/assaultpointsecureadvance.wav");
CAKE.AddChatterVoice("Combine", "Control 100 Percent", "Control is 100 percent this location, no sign of that 647E.", "npc/metropolice/vo/control100percent.wav");
CAKE.AddChatterVoice("Combine", "Overrun", "CP is overrun, we have no containment.", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav");
CAKE.AddChatterVoice("Combine", "Target", "Target my radial!", "npc/combine_soldier/vo/targetmyradial.wav");
CAKE.AddChatterVoice("Combine", "Perimeter", "CP, we need to establish a perimeter at", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav");
CAKE.AddChatterVoice("Combine", "All Units", "CP requests, all units, location, report in!", "npc/metropolice/vo/cprequestsallunitsreportin.wav");
CAKE.AddChatterVoice("Combine", "BOL", "CP, we need airwatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav");
CAKE.AddChatterVoice("Combine", "Administer", "Administer.", "npc/metropolice/vo/administer.wav");
CAKE.AddChatterVoice("Combine", "Affirmative", "Affirmative.", "npc/metropolice/vo/affirmative.wav");
CAKE.AddChatterVoice("Combine", "All Units Move In", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav");
CAKE.AddChatterVoice("Combine", "Amputate", "Amputate.", "npc/metropolice/vo/amputate.wav");
CAKE.AddChatterVoice("Combine", "Anti-Citizen", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav");
CAKE.AddChatterVoice("Combine", "Clear 100", "Clear and Code 100.", "npc/metropolice/vo/clearandcode100.wav");
CAKE.AddChatterVoice("Combine", "Code 100", "Code 100.", "npc/metropolice/vo/code100.wav");
CAKE.AddChatterVoice("Combine", "Citizen", "Citizen.", "npc/metropolice/vo/citizen.wav");
CAKE.AddChatterVoice("Combine", "Copy", "Copy.", "npc/metropolice/vo/copy.wav");
CAKE.AddChatterVoice("Combine", "Cover Me", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav");
CAKE.AddChatterVoice("Combine", "Assist Trespass", "Assist for a criminal trespass!", "npc/metropolice/vo/criminaltrespass63.wav");
CAKE.AddChatterVoice("Combine", "Destroy Cover", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav");
CAKE.AddChatterVoice("Combine", "Don't Move", "Don't move!", "npc/metropolice/vo/dontmove.wav");
CAKE.AddChatterVoice("Combine", "Final Verdict", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav");
CAKE.AddChatterVoice("Combine", "Final Warning", "Final warning!", "npc/metropolice/vo/finalwarning.wav");
CAKE.AddChatterVoice("Combine", "First Warning", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav");
CAKE.AddChatterVoice("Combine", "Get Down", "Get down!", "npc/metropolice/vo/getdown.wav");
CAKE.AddChatterVoice("Combine", "Get Out", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav");
CAKE.AddChatterVoice("Combine", "Suspect One", "I got suspect one here.", "npc/metropolice/vo/gotsuspect1here.wav");
CAKE.AddChatterVoice("Combine", "Help", "Help!", "npc/metropolice/vo/help.wav");
CAKE.AddChatterVoice("Combine", "Running", "He's running!", "npc/metropolice/vo/hesrunning.wav");
CAKE.AddChatterVoice("Combine", "Hold It", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav");
CAKE.AddChatterVoice("Combine", "Move Along Repeat", "I said move along.", "npc/metropolice/vo/isaidmovealong.wav");
CAKE.AddChatterVoice("Combine", "Malcompliance", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav");
CAKE.AddChatterVoice("Combine", "Keep Moving", "Keep moving!", "npc/metropolice/vo/keepmoving.wav");
CAKE.AddChatterVoice("Combine", "Lock Position", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav");
CAKE.AddChatterVoice("Combine", "Trouble", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav");
CAKE.AddChatterVoice("Combine", "Look Out", "Look out!", "npc/metropolice/vo/lookout.wav");
CAKE.AddChatterVoice("Combine", "Minor Hits", "Minor hits, continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav");
CAKE.AddChatterVoice("Combine", "Move", "Move!", "npc/metropolice/vo/move.wav");
CAKE.AddChatterVoice("Combine", "Move Along", "Move along!", "npc/metropolice/vo/movealong3.wav");
CAKE.AddChatterVoice("Combine", "Move Back", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav");
CAKE.AddChatterVoice("Combine", "Move It", "Move it!", "npc/metropolice/vo/moveit2.wav");
CAKE.AddChatterVoice("Combine", "Hardpoint", "Moving to hardpoint.", "npc/metropolice/vo/movingtohardpoint.wav");
CAKE.AddChatterVoice("Combine", "Officer Help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav");
CAKE.AddChatterVoice("Combine", "Privacy", "Possible level three civil privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav");
CAKE.AddChatterVoice("Combine", "Judgement", "Suspect prepare to receive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav");
CAKE.AddChatterVoice("Combine", "Priority Two", "I have a priority two anti-citizen here!", "npc/metropolice/vo/priority2anticitizenhere.wav");
CAKE.AddChatterVoice("Combine", "Prosecute", "Prosecute!", "npc/metropolice/vo/prosecute.wav");
CAKE.AddChatterVoice("Combine", "Amputate Ready", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav");
CAKE.AddChatterVoice("Combine", "Rodger That", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav");
CAKE.AddChatterVoice("Combine", "Search", "Search!", "npc/metropolice/vo/search.wav");
CAKE.AddChatterVoice("Combine", "Shit", "Shit!", "npc/metropolice/vo/shit.wav");
CAKE.AddChatterVoice("Combine", "Sentence Delivered", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav");
CAKE.AddChatterVoice("Combine", "Sterilize", "Sterilize!", "npc/metropolice/vo/sterilize.wav");
CAKE.AddChatterVoice("Combine", "Take Cover", "Take cover!", "npc/metropolice/vo/takecover.wav");
CAKE.AddChatterVoice("Combine", "Restrict", "Restrict!", "npc/metropolice/vo/restrict.wav");
CAKE.AddChatterVoice("Combine", "Restricted", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav");
CAKE.AddChatterVoice("Combine", "Second Warning", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav");
CAKE.AddChatterVoice("Combine", "Verdict", "You want a non-compliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav");
CAKE.AddChatterVoice("Combine", "Backup", "Backup!", "npc/metropolice/vo/backup.wav");
CAKE.AddChatterVoice("Combine", "Apply", "Apply.", "npc/metropolice/vo/apply.wav");
CAKE.AddChatterVoice("Combine", "Restriction", "Terminal restriction zone.", "npc/metropolice/vo/terminalrestrictionzone.wav");
CAKE.AddChatterVoice("Combine", "Complete", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav");
CAKE.AddChatterVoice("Combine", "Location Unknown", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav");
CAKE.AddChatterVoice("Combine", "Can 1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav");
CAKE.AddChatterVoice("Combine", "Can 2", "Pick... up... the can.", "npc/metropolice/vo/pickupthecan2.wav");
CAKE.AddChatterVoice("Combine", "Wrap It", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav");
CAKE.AddChatterVoice("Combine", "Can 3", "I said pickup the can!", "npc/metropolice/vo/pickupthecan3.wav");
CAKE.AddChatterVoice("Combine", "Can 4", "Now, put it in the trash can.", "npc/metropolice/vo/putitinthetrash1.wav");
CAKE.AddChatterVoice("Combine", "Can 5", "I said put it in the trash can!", "npc/metropolice/vo/putitinthetrash2.wav");
CAKE.AddChatterVoice("Combine", "Now Get Out", "Now get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav");
CAKE.AddChatterVoice("Combine", "Haha", "Haha.", "npc/metropolice/vo/chuckle.wav");
CAKE.AddChatterVoice("Combine", "X-Ray", "X-Ray!", "npc/metropolice/vo/xray.wav");
CAKE.AddChatterVoice("Combine", "Patrol", "Patrol!", "npc/metropolice/vo/patrol.wav");
CAKE.AddChatterVoice("Combine", "Serve", "Serve.", "npc/metropolice/vo/serve.wav");
CAKE.AddChatterVoice("Combine", "Knocked Over", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav");
CAKE.AddChatterVoice("Combine", "Watch It", "Watch it!", "npc/metropolice/vo/watchit.wav");
CAKE.AddChatterVoice("Combine", "Restricted Canals", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav");
CAKE.AddChatterVoice("Combine", "505", "Subject is five-oh-five!", "npc/metropolice/vo/subjectis505.wav");
CAKE.AddChatterVoice("Combine", "404", "Possible four-zero-oh here!", "npc/metropolice/vo/possible404here.wav");
CAKE.AddChatterVoice("Combine", "Vacate", "Vacate citizen!", "npc/metropolice/vo/vacatecitizen.wav");
CAKE.AddChatterVoice("Combine", "Escapee", "Priority two escapee.", "npc/combine_soldier/vo/prioritytwoescapee.wav");
CAKE.AddChatterVoice("Combine", "Objective", "Priority one objective.", "npc/combine_soldier/vo/priority1objective.wav");
CAKE.AddChatterVoice("Combine", "Payback", "Payback.", "npc/combine_soldier/vo/payback.wav");
CAKE.AddChatterVoice("Combine", "Got Him Now", "Affirmative, we got him now.", "npc/combine_soldier/vo/affirmativewegothimnow.wav");
CAKE.AddChatterVoice("Combine", "Antiseptic", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav");
CAKE.AddChatterVoice("Combine", "Cleaned", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav");
CAKE.AddChatterVoice("Combine", "Engaged Cleanup", "Engaged in cleanup.", "npc/combine_soldier/vo/engagedincleanup.wav");
CAKE.AddChatterVoice("Combine", "Engaging", "Engaging.", "npc/combine_soldier/vo/engaging.wav");
CAKE.AddChatterVoice("Combine", "Full Response", "Executing full response.", "npc/combine_soldier/vo/executingfullresponse.wav");
CAKE.AddChatterVoice("Combine", "Heavy Resistance", "Overwatch advise, we have heavy resistance.", "npc/combine_soldier/vo/heavyresistance.wav");
CAKE.AddChatterVoice("Combine", "Inbound", "Inbound.", "npc/combine_soldier/vo/inbound.wav");
CAKE.AddChatterVoice("Combine", "Lost Contact", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav");
CAKE.AddChatterVoice("Combine", "Move In", "Move in!", "npc/combine_soldier/vo/movein.wav");
CAKE.AddChatterVoice("Combine", "Harden Position", "Harden that position!", "npc/combine_soldier/vo/hardenthatposition.wav");
CAKE.AddChatterVoice("Combine", "Go Sharp", "Go sharp, go sharp!", "npc/combine_soldier/vo/gosharpgosharp.wav");
CAKE.AddChatterVoice("Combine", "Delivered", "Delivered.", "npc/combine_soldier/vo/delivered.wav");
CAKE.AddChatterVoice("Combine", "Necrotics Inbound", "Necrotics, inbound!", "npc/combine_soldier/vo/necroticsinbound.wav");
CAKE.AddChatterVoice("Combine", "Necrotics", "Necrotics.", "npc/combine_soldier/vo/necrotics.wav");
CAKE.AddChatterVoice("Combine", "Outbreak", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav");
CAKE.AddChatterVoice("Combine", "Copy That", "Copy that.", "npc/combine_soldier/vo/copythat.wav");
CAKE.AddChatterVoice("Combine", "Outbreak Status", "Outbreak status is code.", "npc/combine_soldier/vo/outbreakstatusiscode.wav");
CAKE.AddChatterVoice("Combine", "Overwatch", "Overwatch!", "npc/combine_soldier/vo/overwatch.wav");
CAKE.AddChatterVoice("Combine", "Preserve", "Preserve!", "npc/metropolice/vo/preserve.wav");
CAKE.AddChatterVoice("Combine", "Pressure", "Pressure!", "npc/metropolice/vo/pressure.wav");
CAKE.AddChatterVoice("Combine", "Phantom", "Phantom!", "npc/combine_soldier/vo/phantom.wav");
CAKE.AddChatterVoice("Combine", "Stinger", "Stinger!", "npc/combine_soldier/vo/stinger.wav");
CAKE.AddChatterVoice("Combine", "Shadow", "Shadow!", "npc/combine_soldier/vo/shadow.wav");
CAKE.AddChatterVoice("Combine", "Savage", "Savage!", "npc/combine_soldier/vo/savage.wav");
CAKE.AddChatterVoice("Combine", "Reaper", "Reaper!", "npc/combine_soldier/vo/reaper.wav");
CAKE.AddChatterVoice("Combine", "Victor", "Victor!", "npc/metropolice/vo/victor.wav");
CAKE.AddChatterVoice("Combine", "Sector", "Sector!", "npc/metropolice/vo/sector.wav");
CAKE.AddChatterVoice("Combine", "Inject", "Inject!", "npc/metropolice/vo/inject.wav");
CAKE.AddChatterVoice("Combine", "Dagger", "Dagger!", "npc/combine_soldier/vo/dagger.wav");
CAKE.AddChatterVoice("Combine", "Blade", "Blade!", "npc/combine_soldier/vo/blade.wav");
CAKE.AddChatterVoice("Combine", "Razor", "Razor!", "npc/combine_soldier/vo/razor.wav");
CAKE.AddChatterVoice("Combine", "Nomad", "Nomad!", "npc/combine_soldier/vo/nomad.wav");
CAKE.AddChatterVoice("Combine", "Judge", "Judge!", "npc/combine_soldier/vo/judge.wav");
CAKE.AddChatterVoice("Combine", "Ghost", "Ghost!", "npc/combine_soldier/vo/ghost.wav");
CAKE.AddChatterVoice("Combine", "Sword", "Sword!", "npc/combine_soldier/vo/sword.wav");
CAKE.AddChatterVoice("Combine", "Union", "Union!", "npc/metropolice/vo/union.wav");
CAKE.AddChatterVoice("Combine", "Helix", "Helix!", "npc/combine_soldier/vo/helix.wav");
CAKE.AddChatterVoice("Combine", "Storm", "Storm!", "npc/combine_soldier/vo/storm.wav");
CAKE.AddChatterVoice("Combine", "Spear", "Spear!", "npc/combine_soldier/vo/spear.wav");
CAKE.AddChatterVoice("Combine", "Vamp", "Vamp!", "npc/combine_soldier/vo/vamp.wav");
CAKE.AddChatterVoice("Combine", "Nova", "Nova!", "npc/combine_soldier/vo/nova.wav");
CAKE.AddChatterVoice("Combine", "Mace", "Mace!", "npc/combine_soldier/vo/mace.wav");
CAKE.AddChatterVoice("Combine", "Grid", "Grid!", "npc/combine_soldier/vo/grid.wav");
CAKE.AddChatterVoice("Combine", "Kilo", "Kilo!", "npc/combine_soldier/vo/kilo.wav");
CAKE.AddChatterVoice("Combine", "Echo", "Echo!", "npc/combine_soldier/vo/echo.wav");
CAKE.AddChatterVoice("Combine", "Dash", "Dash!", "npc/combine_soldier/vo/dash.wav");
CAKE.AddChatterVoice("Combine", "Apex", "Apex!", "npc/combine_soldier/vo/apex.wav");
CAKE.AddChatterVoice("Combine", "Jury", "Jury!", "npc/metropolice/vo/jury.wav");
CAKE.AddChatterVoice("Combine", "King", "King!", "npc/metropolice/vo/king.wav");
CAKE.AddChatterVoice("Combine", "Lock", "Lock!", "npc/metropolice/vo/lock.wav");
CAKE.AddChatterVoice("Combine", "Vice", "Vice!", "npc/metropolice/vo/vice.wav");
CAKE.AddChatterVoice("Combine", "Zero", "Zero!", "npc/metropolice/vo/zero.wav");
CAKE.AddChatterVoice("Combine", "Zone", "Zone!", "npc/metropolice/vo/zone.wav");
CAKE.AddChatterVoice("Combine", "There he is", "There he is.", "npc/metropolice/vo/thereheis.wav");
CAKE.AddChatterVoice("Combine", "3", "Three.", "npc/metropolice/vo/three.wav");
CAKE.AddChatterVoice("Combine", "Transit", "Transit Block.", "npc/metropolice/vo/transitblock.wav");
CAKE.AddChatterVoice("Combine", "2", "Two.", "npc/metropolice/vo/two.wav");
CAKE.AddChatterVoice("Combine", "UPI", "UPI.", "npc/metropolice/vo/upi.wav");
CAKE.AddChatterVoice("Combine", "Vacate", "Vacate Citizen.", "npc/metropolice/vo/vacatecitizen.wav");
CAKE.AddChatterVoice("Combine", "Viscerator", "Viscerator Deployed.", "npc/metropolice/vo/visceratordeployed.wav");
CAKE.AddChatterVoice("Combine", "Viscerator is OC", "Watch it, Viscerator Is OC!", "npc/metropolice/vo/visceratorisoc.wav");
CAKE.AddChatterVoice("Combine", "Vi Off Grid", "Viscerator is off grid.", "npc/metropolice/vo/visceratorisoffgrid.wav");
CAKE.AddChatterVoice("Combine", "Waste River", "Waste River.", "npc/metropolice/vo/wasteriver.wav");
CAKE.AddChatterVoice("Combine", "Socialstable", "We are socialstable on this location.", "npc/metropolice/vo/wearesocialstablethislocation.wav");
CAKE.AddChatterVoice("Combine", "10-108", "We have 10-108", "npc/metropolice/vo/wehave10-108.wav");
CAKE.AddChatterVoice("Combine", "Work Force", "Work force intake.", "npc/metropolice/vo/workforceintake.wav");
CAKE.AddChatterVoice("Combine", "Yellow", "Yellow.", "npc/metropolice/vo/yellow.wav");
CAKE.AddChatterVoice("Combine", "On visial", "Acquiring on visual.", "npc/metropolice/vo/acquiringonvisual.wav");
CAKE.AddChatterVoice("Combine", "BOL 2", "All units, BOL, we have 34 hits at", "npc/metropolice/vo/allunitsbol34sat.wav");
CAKE.AddChatterVoice("Combine", "Close on Suspect", "All units, close on suspect.", "npc/metropolice/vo/allunitscloseonsuspect.wav");
CAKE.AddChatterVoice("Combine", "647E", "Anyone pick up uuhh.. 647E?", "npc/metropolice/vo/anyonepickup647e.wav");
CAKE.AddChatterVoice("Combine", "At Checkpoint", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav");
CAKE.AddChatterVoice("Combine", "Back Me Up", "Back me up, im out!.", "npc/metropolice/vo/backmeupImout.wav");
CAKE.AddChatterVoice("Combine", "Break Cover", "Break his cover!.", "npc/metropolice/vo/breakhiscover.wav");
CAKE.AddChatterVoice("Combine", "Bugs", "Bugs.", "npc/metropolice/vo/bugs.wav");
CAKE.AddChatterVoice("Combine", "Miscount", "Check for... Miscount.", "npc/metropolice/vo/checkformiscount.wav");
CAKE.AddChatterVoice("Combine", "Code 7", "Code seven.", "npc/metropolice/vo/code7.wav");
CAKE.AddChatterVoice("Combine", "Condemned", "Condemned Zone.", "npc/metropolice/vo/condemnedzone.wav");
CAKE.AddChatterVoice("Combine", "Contact With", "Contact with priority two.", "npc/metropolice/vo/contactwithpriority2.wav");
CAKE.AddChatterVoice("Combine", "Converging", "Converging!", "npc/metropolice/vo/converging.wav");
CAKE.AddChatterVoice("Combine", "Compromised", "CP is compromised, We have stablished.", "npc/metropolice/vo/cpiscompromised.wav");
CAKE.AddChatterVoice("Combine", "Overrun", "CP is overrun, We have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav");
CAKE.AddChatterVoice("Combine", "Perimeter", "CP We need to establish a Perimeter at...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav");
CAKE.AddChatterVoice("Combine", "Defender", "Defender!", "npc/metropolice/vo/defender.wav");
CAKE.AddChatterVoice("Combine", "Deserviced", "Deserviced Area.", "npc/metropolice/vo/deservicedarea.wav");
CAKE.AddChatterVoice("Combine", "Document", "Document.", "npc/metropolice/vo/document.wav");
CAKE.AddChatterVoice("Combine", "8", "Eight.", "npc/metropolice/vo/eight.wav");
CAKE.AddChatterVoice("Combine", "10", "Ten.", "npc/metropolice/vo/ten.wav");
CAKE.AddChatterVoice("Combine", "Examine", "Examine.", "npc/metropolice/vo/examine.wav");
CAKE.AddChatterVoice("Combine", "Expired", "Expired.", "npc/metropolice/vo/expired.wav");
CAKE.AddChatterVoice("Combine", "5", "Five.", "npc/metropolice/vo/five.wav");
CAKE.AddChatterVoice("Combine", "4", "Four.", "npc/metropolice/vo/four.wav");
CAKE.AddChatterVoice("Combine", "Take a look", "Going to take a look.", "npc/metropolice/vo/goingtotakealook.wav");
CAKE.AddChatterVoice("Combine", "Grenade", "Grenade!", "npc/metropolice/vo/grenade.wav");
CAKE.AddChatterVoice("Combine", "Hardpoint Scan", "Hardpoint Scanning.", "npc/metropolice/vo/hardpointscanning.wav");
CAKE.AddChatterVoice("Combine", "Hero", "Hero.", "npc/metropolice/vo/hero.wav");
CAKE.AddChatterVoice("Combine", "Up There", "Hes up there.", "npc/metropolice/vo/hesupthere.wav");
CAKE.AddChatterVoice("Combine", "High Priority", "High Priority Region.", "npc/metropolice/vo/highpriorityregion.wav");
CAKE.AddChatterVoice("Combine", "Infection", "Infection.", "npc/metropolice/vo/infection.wav");
CAKE.AddChatterVoice("Combine", "Industrial Zone", "Industrial Zone.", "npc/metropolice/vo/industrialzone.wav");
CAKE.AddChatterVoice("Combine", "Interlock", "Interlock.", "npc/metropolice/vo/interlock.wav");
CAKE.AddChatterVoice("Combine", "Is at hardpoint", "At hardpoint, ready to prosecute.", "npc/metropolice/vo/isathardpointreadytoprosecute.wav");
CAKE.AddChatterVoice("Combine", "Down", "Is down!.", "npc/metropolice/vo/isdown.wav");
CAKE.AddChatterVoice("Combine", "Is go", "Is go.", "npc/metropolice/vo/isgo.wav");
CAKE.AddChatterVoice("Combine", "Is moving in", "Is moving in.", "npc/metropolice/vo/ismovingin.wav");
CAKE.AddChatterVoice("Combine", "Passive", "Is passive.", "npc/metropolice/vo/ispassive.wav");
CAKE.AddChatterVoice("Combine", "Is ready go", "Is ready to go.", "npc/metropolice/vo/isreadytogo.wav");
CAKE.AddChatterVoice("Combine", "Line", "Line.", "npc/metropolice/vo/line.wav");
CAKE.AddChatterVoice("Combine", "Location", "Location.", "npc/metropolice/vo/location.wav");
CAKE.AddChatterVoice("Combine", "Look out", "Look out!", "npc/metropolice/vo/lookout.wav");
CAKE.AddChatterVoice("Combine", "Malignant", "Malignant.", "npc/metropolice/vo/malignant.wav");
CAKE.AddChatterVoice("Combine", "Meters", "Meters.", "npc/metropolice/vo/meters.wav");
CAKE.AddChatterVoice("Combine", "9", "Nine.", "npc/metropolice/vo/nine.wav");
CAKE.AddChatterVoice("Combine", "1", "One.", "npc/metropolice/vo/one.wav");
CAKE.AddChatterVoice("Combine", "Pacifying", "Pacifying.", "npc/metropolice/vo/pacifying.wav");
CAKE.AddChatterVoice("Combine", "Production Block", "Production Block.", "npc/metropolice/vo/productionblock.wav");
CAKE.AddChatterVoice("Combine", "PT", "PT Go again.", "npc/metropolice/vo/ptgoagain.wav");
CAKE.AddChatterVoice("Combine", "Quick", "Quick!", "npc/metropolice/vo/quick.wav");
CAKE.AddChatterVoice("Combine", "Ready judge", "Ready to judge!", "npc/metropolice/vo/readytojudge.wav");
CAKE.AddChatterVoice("Combine", "Ready prosecute", "Ready to prosecute!", "npc/metropolice/vo/readytoprosecute.wav");
CAKE.AddChatterVoice("Combine", "Repurposed", "Repurposed Area.", "npc/metropolice/vo/repurposedarea.wav");
CAKE.AddChatterVoice("Combine", "Responding", "Responding.", "npc/metropolice/vo/responding.wav");
CAKE.AddChatterVoice("Combine", "Roller", "Roller!", "npc/metropolice/vo/roller.wav");
CAKE.AddChatterVoice("Combine", "7", "Seven.", "npc/metropolice/vo/seven.wav");
CAKE.AddChatterVoice("Combine", "6", "Six.", "npc/metropolice/vo/six.wav");
CAKE.AddChatterVoice("Combine", "Stick", "Stick.", "npc/metropolice/vo/stick.wav");
CAKE.AddChatterVoice("Combine", "Storm system", "Storm System.", "npc/metropolice/vo/stormsystem.wav");
CAKE.AddChatterVoice("Combine", "Subject high speed", "All Units be adviced, Subject is now high speed.", "npc/metropolice/vo/subjectisnowhighspeed.wav");
CAKE.AddChatterVoice("Combine", "Subject Moved to", "Subject has Moved now to...", "npc/metropolice/vo/subjecthasmovednowto.wav");
CAKE.AddChatterVoice("Combine", "Suspend", "Suspend.", "npc/metropolice/vo/suspend.wav");
CAKE.AddChatterVoice("Combine", "Tag Biotic", "Tag one Biotic.", "npc/metropolice/vo/tagonebiotic.wav");
CAKE.AddChatterVoice("Combine", "Tap", "Tap.", "npc/metropolice/vo/tap.wav");
CAKE.AddChatterVoice("Combine", "Team Position", "Team in position, advance.", "npc/metropolice/vo/teaminpositionadvance.wav");
CAKE.AddChatterVoice("Combine", "Grenade 2", "Thats a grenade!", "npc/metropolice/vo/thatsagrenade.wav");
CAKE.AddChatterVoice("Combine", "Hammer", "Hammer.", "npc/combine_soldier/vo/hammer.wav");
CAKE.AddChatterVoice("Combine", "Hunter", "Hunter.", "npc/combine_soldier/vo/hunter.wav");
CAKE.AddChatterVoice("Combine", "Ice", "Ice.", "npc/combine_soldier/vo/ice.wav");
CAKE.AddChatterVoice("Combine", "Jet", "Jet.", "npc/combine_soldier/vo/jet.wav");
CAKE.AddChatterVoice("Combine", "One down", "One down!", "npc/combine_soldier/vo/onedown.wav");
CAKE.AddChatterVoice("Combine", "Overwatch reinforcement", "Overwatch request reinforcement.", "npc/combine_soldier/vo/overwatchrequestreinforcement.wav");
CAKE.AddChatterVoice("Combine", "Overwatch team down", "Overwatch team is down, Sector is not in control.", "npc/combine_soldier/vo/overwatchteamisdown.wav");
CAKE.AddChatterVoice("Combine", "Ranger", "Ranger.", "npc/combine_soldier/vo/ranger.wav");
CAKE.AddChatterVoice("Combine", "Ready weapons", "Ready weapons.", "npc/combine_soldier/vo/readyweapons.wav");
CAKE.AddChatterVoice("Combine", "Scar", "Scar.", "npc/combine_soldier/vo/scar.wav");
CAKE.AddChatterVoice("Combine", "Secure", "Secure", "npc/combine_soldier/vo/secure.wav");
CAKE.AddChatterVoice("Combine", "Stab", "Stab.", "npc/combine_soldier/vo/stab.wav");
CAKE.AddChatterVoice("Combine", "Slam", "Slam.", "npc/combine_soldier/vo/slam.wav");
CAKE.AddChatterVoice("Combine", "Slash", "Slash.", "npc/combine_soldier/vo/slash.wav");
CAKE.AddChatterVoice("Combine", "Star", "Star", "npc/combine_soldier/vo/star.wav");
CAKE.AddChatterVoice("Combine", "Target at", "Target is at", "npc/combine_soldier/vo/targetisat.wav");
CAKE.AddChatterVoice("Combine", "Target one", "Target one.", "npc/combine_soldier/vo/targetone.wav");
CAKE.AddChatterVoice("Combine", "Viscon", "Viscon.", "npc/combine_soldier/vo/viscon.wav");
CAKE.AddChatterVoice("Combine", "Uniform", "Uniform.", "npc/combine_soldier/vo/uniform.wav");
CAKE.AddChatterVoice("Combine", "Closing", "Closing.", "npc/combine_soldier/vo/closing.wav");
CAKE.AddChatterVoice("Combine", "Degrees", "Degrees.", "npc/combine_soldier/vo/degrees.wav");
CAKE.AddChatterVoice("Combine", "Flush", "Flush.", "npc/combine_soldier/vo/flush.wav");
CAKE.AddChatterVoice("Combine", "Fist", "Fist.", "npc/combine_soldier/vo/fist.wav");
CAKE.AddChatterVoice("Combine", "Leader", "Leader.", "npc/combine_soldier/vo/leader.wav");
CAKE.AddChatterVoice("Combine", "Sharp zone", "Sharp Zone.", "npc/combine_soldier/vo/sharpzone.wav");
CAKE.AddChatterVoice("Combine", "Striker", "Striker.", "npc/combine_soldier/vo/striker.wav");
CAKE.AddChatterVoice("Combine", "Unit closing", "Unit is closing.", "npc/combine_soldier/vo/unitisclosing.wav");
CAKE.AddChatterVoice("Combine", "Unit moving in", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav");
CAKE.AddChatterVoice("Combine", "Unit inbound", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav");

